### ISSUE TITLE
Suggest adding clearfix to extended posts twig.

### ISSUE THREAD

**Issue by briancwelch** [presscodes/maera#142]
https://github.com/presscodes/maera/blob/master/views/widget-extended-posts.twig#L22

Suggest changing to:

		</article>
		{{ clearfix() }}

**Comment by aristath** [comment]
We've included some common styles on the [style.css](https://github.com/presscodes/maera/blob/master/style.css) file.
Among these we also have styles for properly handling `screen-reader-text` classes as well as `clearfix` so we can use these on all shells. :+1: 
So no need fo `{{ clearfix() }}`, we can use it like `<div class="clearfix"></div>`

**Comment by briancwelch** [comment]
Excellent!
