### ISSUE TITLE
Add-ons tab link broken

### ISSUE THREAD

**Issue by alicam** [presscodes/maera#163]
I try to click on the add-ons tab (on version of Maera downloaded today) and it directs me here:

/wp-admin/themes.php?page=maera-ri

Which displays the usual WP permissions error: "You do not have sufficient permissions to access this page."

Not tried diagnosing.

A

**Comment by fovoc** [comment]
Hey there,

we just removed the Licensing and Addons tab from admin theme options as you can see in b3447672fcf81e9bf7ea60e5c495417fa8cc3d64. Feel free to pull latest commit to get rid of those.

Hope that helps,
Dimitris
